// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI-инструменты (prisma db push, migrate) используют этот URL.
    // Прямое подключение (порт 5432), потому что pgBouncer
    // не поддерживает prepared statements, нужные для миграций.
    // Приложение использует pooler-URL через PrismaClient — см. lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
